# 배열 초기화 
<b> 1. np.zeros : 0으로 초기화 </b> <br>
<b> 2. np.ones : 1으로 초기화 </b> <br>
<b> 3. np.full : 지정한 수로 초기화 </b> <br>
<b> 4. np.eye : 대각선으로 대칭되는 Matrix 생성 </b> <br>
<b> 5. np.random.random : Rnadom 값으로 초기화 </b> <br>

In [26]:
import numpy as np 
a = np.zeros((2,2))  
print (a)              
    
b = np.ones((1,2))   # Create an array of all ones
print (b)              

c = np.full((2,2), 7) # Create a constant array
print (c)               # 

d = np.eye(4)        # Create a 2x2 identity matrix
print (d)              
    
e = np.random.random((2,2)) # Create an array filled with random values
print (e)                     

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[ 7.  7.]
 [ 7.  7.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 0.02649794  0.26402113]
 [ 0.13781099  0.4178478 ]]


/opt/conda/lib/python3.5/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


# 배열 접근 
기본적으로 Numpy는 Python 과 동일하게 메모리 참조를 사용하기 때문에 별도로 Clone 등을 하지 않는한 같은 메모리를 참조하게 된다. <br>
아래의 예제는 배열에 접근하는 두가지 방법을 보여준다. a[0] 과 같이 0번 배열에 접근하거나, a[0:2] 과 같이 특정 범위에 접근 할 수 있다. 

In [28]:
#1차원 배열의 예 
x = np.array([1,2,3,4])
print(x[0])
print(x[1])
print(x[0:2])

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(b)
print (a[0, 1])   # Prints "2"
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print (a[0, 1])   # Prints "77"

1
2
[1 2]
[[2 3]
 [6 7]]
2
77


# 특정 Row, Col 선택 
a[:] 와 같은 형태로 배열을 지정하면 전체 선택의 의미로, a[:, 0:2] 와 같이 지정하면 y 축이 0,1 인 데이터 전체를 가지고 온다. 이런 패턴을 응용하면 아래와 같이 특정 row, col 을 선택해서 가지고 오는 것은 어렵지 않다. 

In [10]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])


row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print (row_r1, row_r1.shape ) # Prints "[5 6 7 8] (4,)"
print (row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print (col_r2, col_r2.shape)  # Prints "[[ 2]             

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


# 배열 Index 로 접근 
당연히 범위가 아니라 특정 포인트를 선택하여 접근할 수도 있다. a[0:2] 와 a[[0,1]은 같은 결과를 출력한다. <br>
같은 방법으로 특정 데이터 Index만 추출할 수 있다.  

In [25]:
a = np.array([[1,2], [3, 4], [5, 6]])

# 배열 포인터 접근을 다시 배열로 할 수 있다. 
# 배열 접근은 첫번재 파라메터가 1차원, 두번째가 2차원 이런 식이다. 
print(a[[0,1,2], 0])
print(a[[0,1,2], 1])
print(a[[0,1], [0,1]])

# 아래의 두개는 같다. 
print (a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"
print (np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# 당연히 아래의 두개도 같다. 
print (a[[0, 0], [1, 1]])  # Prints "[2 2]"
print (np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 3 5]
[2 4 6]
[1 4]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


# 특정 배열의 값을 변경 
위와 같이 특정 배열에 접근하여 그 값을 변경할 수 있다. 

In [30]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print (a)  # prints "array([[ 1,  2,  3],
         #                [ 4,  5,  6],
         #                [ 7,  8,  9],
         #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print (a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print (a)  # prints "array([[11,  2,  3],

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


# 조건판단
조건판단을 통해 조건에 부합하는 데이터만 추출 할 수 있다 .

In [31]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
print (bool_idx )     # Prints "[[False False]
print (a[bool_idx] ) # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print (a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


# 데이터 타입
데이터 타입은 데이터의 형태혹은 dtype 파라메터를 통해서 강제로 지정 가능하다. 

In [33]:

x = np.array([1, 2])  # Let numpy choose the datatype
print (x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])  # Let numpy choose the datatype
print (x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)  # Force a particular datatype
print (x.dtype)                         # Prints "int64"

int64
float64
int64


# Array 사칙연산 
더하기 곱하기 나누기 루트 등 다양한 연산 수행 가능 

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print x + y
print np.add(x, y)

# Array 간의 빼기 연산 
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print x - y
print np.subtract(x, y)

# 곱하기 연산
# [[ 5.0 12.0]
#  [21.0 32.0]]
print x * y
print np.multiply(x, y)

# E나누기 연산
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print x / y
print np.divide(x, y)

# 루트 연산 
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print np.sqrt(x)

# 간단한 연산 기능 
sum, avg, min, max 등 간단한 연산 기능을 사용할 수 있다. 

In [59]:
x = np.array([[1,2],[3,4]])
print (np.sum(x))  # Compute sum of all elements; prints "10"
print (np.sum(x, axis=0))  
print (np.sum(x, axis=1))  

print (np.max(x, axis=0))  
print (np.min(x, axis=0))  
print (np.max(x, axis=1))  
print (np.min(x, axis=1))  


10
[4 6]
[3 7]
[3 4]
[1 2]
[2 4]
[1 3]


# Transpose 
T method 를 사용해서 메트릭스를 변환할 수 있다. 단, 1차원 Matrix 에서는 동작하지 않는다. 

In [60]:
x = np.array([[1,2], [3,4]])
print (x)    # Prints "[[1 2]
           #          [3 4]]"
print (x.T)  # Prints "[[1 3]
           #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print (v)    # Prints "[1 2 3]"
print (v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


# Broadcasting
서로다른 차원의 Matrix 을 연산 할 수 있다. 

In [61]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print (y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


# Broadcasting 
위와 같이 Loop 연산 없이 동일한 Matrix 를 tile 메서드를 이용하여 큰 Matrix 와 동일한 사이즈가 되도록 쌓은 후 연산을 할 수 있다. 

In [63]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print (vv)                 
y = x + vv  # Add x and vv elementwise
print (y) 

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


# reshape 
reshape method 를 통해 배열의 Shape 을 바꾸고 연산을 할 수 있다. <br> ※ reshape 시 -1 은 무한대와 같은 역할을 하게 된다. 

In [70]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
print (np.reshape(v, (3, 1)))
print (np.reshape(v, (-1, 1)))
print (np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
v = np.array([1,2,3])
x = np.array([[1,2,3], [4,5,6]])
print (x + v)

# Add a vector to each column of a matrix
print ((x.T + w).T)
# output.
print (x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
print (x * 2)

[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]
[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
