# Word Representation

### One Hot Vector를 통한 출력

In [30]:
from konlpy.tag import Mecab

qna_data = [
                ['안녕', '만나서 반가워']
                ,['넌누구니', '나는 AI 봇이란다.']
#                 ,['피자 주문 할께', '페파로니 주문해줘']
#                ,['음료는 멀로', '콜라로 해줘']
            ]
mecab = Mecab('/usr/local/lib/mecab/dic/mecab-ko-dic')

train_data = list(map(lambda x : mecab.morphs(' '.join(x)) , qna_data))

import itertools
train_data = list(itertools.chain.from_iterable(train_data))
#train_data = list(set(train_data))

print(list(train_data))

['안녕', '만나', '서', '반가워', '넌', '누구', '니', '나', '는', 'AI', '봇', '이', '란다', '.']


In [31]:
import numpy as np
bucket = np.zeros(len(train_data), dtype=np.float)

for word in train_data :
    bucket_temp = bucket.copy()
    np.put(bucket_temp, train_data.index(word), 1)
    print(bucket_temp)

[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]


## Word to Vector (By Gensim)
### W2V를 통해 출력해보자

In [32]:
from gensim.models import word2vec

In [33]:
train_data = [train_data]
print(train_data)

model = word2vec.Word2Vec(size=50, window=2, min_count=1)
model.build_vocab(train_data)
model.train(train_data)
print("model check : {0}".format(model))

[['안녕', '만나', '서', '반가워', '넌', '누구', '니', '나', '는', 'AI', '봇', '이', '란다', '.']]
model check : Word2Vec(vocab=14, size=50, alpha=0.025)


In [34]:
import os  
file_path = './model'
if not os.path.exists(file_path):
    os.makedirs(file_path)
model.save(file_path + "/w2v.bin")
model = word2vec.Word2Vec.load("./model/w2v.bin")
print("model load check : {0}".format(model))

model load check : Word2Vec(vocab=14, size=50, alpha=0.025)


In [35]:
print(model.wv.index2word)

['넌', '안녕', '니', '반가워', '란다', '나', '는', '서', '봇', '누구', 'AI', '만나', '이', '.']


### 안녕, AI등 값의 Vector값 출력 

In [36]:
print(model['안녕'])

[ 0.00906392  0.00662671 -0.00857101  0.00127208  0.00892127  0.00774612
  0.00918776  0.00846652 -0.0029425  -0.00767829 -0.00302397  0.00048057
 -0.00385544 -0.00359789 -0.00413739 -0.00219288 -0.00013363  0.00810544
  0.00272209 -0.00583092 -0.00993142  0.00107607  0.00708261  0.00720571
 -0.00511372  0.00288195 -0.00772363  0.00142288  0.00294792 -0.00210383
  0.00157649  0.00214393 -0.00589636  0.00866197 -0.00011011  0.00509825
 -0.00366211 -0.00307068  0.00051911 -0.00247017 -0.00681107 -0.00360943
  0.00397343 -0.00119501 -0.00985976  0.00707069  0.0087037  -0.00117793
 -0.00323435 -0.00720304]


In [37]:
print(model['AI'])

[-0.00625702 -0.00240439  0.00722755 -0.00785832 -0.0044202  -0.0055006
 -0.00706359  0.00403029  0.00310217 -0.00281276 -0.00457072  0.00547957
 -0.00951945  0.00758849  0.00087858  0.00763961 -0.00636545 -0.00736459
  0.00201024 -0.00974274 -0.00481566 -0.00258274 -0.00668924 -0.00819318
 -0.00582225 -0.00011333 -0.00600814 -0.0022568   0.00999346 -0.00148616
 -0.00932303 -0.0006933   0.00017863 -0.00696899  0.00237124 -0.0024723
 -0.00909115  0.00325816 -0.00215428 -0.00141546 -0.00658541 -0.00152294
  0.00605505 -0.00082731  0.00141879 -0.00180908  0.00013175  0.00364501
  0.00332046  0.0029849 ]


In [38]:
result1 = model.most_similar(positive='나', negative='', topn=10)
print(result1)

[('서', 0.3277257978916168), ('넌', 0.32181084156036377), ('란다', 0.12879055738449097), ('.', 0.04148875176906586), ('안녕', 0.026515774428844452), ('니', 0.011996626853942871), ('는', -0.01740662008523941), ('봇', -0.039780400693416595), ('반가워', -0.07147873938083649), ('이', -0.12071488797664642)]


In [39]:
from sklearn.manifold import TSNE
import pandas as pd
import matplotlib.pyplot as plt


font_name = matplotlib.font_manager.FontProperties(
                fname="/usr/share/fonts/truetype/nanum/NanumGothic.ttf"  # 한글 폰트 위치를 넣어주세요
            ).get_name()
vocab = model.wv.index2word
matplotlib.rc('font', family=font_name)
tsne = TSNE(n_components=2)
X_tsne = tsne.fit_transform(X) #t-분포 확률적 임베딩(t-SNE)은 데이터의 차원 축소에 사용
df = pd.concat([pd.DataFrame(X_tsne),
                pd.Series(vocab)],
               axis=1)

df.columns = ['x', 'y', 'word']
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
print(df)
ax.scatter(df['x'], df['y'])
ax.set_xlim(df['x'].max(), df['x'].min())
ax.set_ylim(df['y'].max(), df['y'].min())
for i, txt in enumerate(df['word']):
    ax.annotate(txt, (df['x'].iloc[i], df['y'].iloc[i]))
plt.show()

NameError: name 'matplotlib' is not defined