# SparseTensorExample
* 듬성듬성한 데이터를 표현하는 방법

* SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
>[[1, 0, 0, 0]<br>
>[0, 0, 2, 0]<br>
>[0, 0, 0, 0]]

In [23]:
import tensorflow as tf
import numpy as np



spase_data = ['Bachelors', 'Some-college', 'male','female']

# SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
#tf.SparseTensor(
#          indices=[[i, 0] for i in range(df[k].size)],
#          values=df[k].values,
#          dense_shape=[df[k].size, 1])

spase_tensor = tf.SparseTensor(indices = [[i,0] for i in range(len(spase_data))]
                               , values = spase_data
                               , dense_shape = [len(spase_data), 1])#표현 행렬

spase_tensor2 = tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
dense = tf.sparse_tensor_to_dense(spase_tensor, default_value='')
dense2 = tf.sparse_tensor_to_dense(spase_tensor2)

sess = tf.InteractiveSession()
print(spase_tensor.eval())
print(spase_tensor2.eval())
print(dense.eval())
print(dense2.eval())
sess.close()


SparseTensorValue(indices=array([[0, 0],
       [1, 0],
       [2, 0],
       [3, 0]]), values=array([b'Bachelors', b'Some-college', b'male', b'female'], dtype=object), dense_shape=array([4, 1]))
SparseTensorValue(indices=array([[0, 0],
       [1, 2]]), values=array([1, 2], dtype=int32), dense_shape=array([3, 4]))
[[b'Bachelors']
 [b'Some-college']
 [b'male']
 [b'female']]
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]]
