In [1]:
import tensorflow as tf
import numpy as np

a = np.zeros([2,2])
print(a)
print(a.reshape([1,4]))

t = tf.zeros([2,2])
sess = tf.Session()
print(sess.run(t))
print(sess.run(tf.reshape(t,[1,4])))
sess.close()

[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.  0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.  0.  0.]]
