In [1]:
import numpy as np
a = np.zeros((1,3,1,2))
print(a)
print(np.squeeze(a))

[[[[ 0.  0.]]

  [[ 0.  0.]]

  [[ 0.  0.]]]]
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [3]:
import tensorflow as tf
ta = tf.zeros((1,3,1,2))

with tf.Session() as sess:
    print(sess.run(ta))
    print(sess.run(tf.squeeze(ta)))

[[[[ 0.  0.]]

  [[ 0.  0.]]

  [[ 0.  0.]]]]
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
