In [1]:
import numpy as np

a = np.zeros((2,2))
print(a)
b = np.ones((2,2))
print(b)

print(np.sum(b, axis=1))

print(a.shape)
print(np.reshape(a,(1,4)))

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]
 [ 1.  1.]]
[ 2.  2.]
(2, 2)
[[ 0.  0.  0.  0.]]


In [2]:
import tensorflow as tf

sess = tf.InteractiveSession()
a = tf.zeros((2,2))
b = tf.ones((2,2))
print(tf.reduce_sum(b, reduction_indices=1).eval())

print(a.get_shape())
print(tf.reshape(a, (1,4)).eval())

sess.close()

[ 2.  2.]
(2, 2)
[[ 0.  0.  0.  0.]]
