In [2]:
import tensorflow as tf

scalar1 = tf.constant(10000)

vector1 = tf.constant([1,2,3,4,5])

matrix1 = tf.constant([[1,2,3],[4,5,6]])

cube1 = tf.constant([[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9]]])

print(scalar1.get_shape())
print(vector1.get_shape())
print(matrix1.get_shape())
print(cube1.get_shape())

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
print(sess.run(scalar1))
print(sess.run(cube1))
sess.close()

()
(5,)
(2, 3)
(3, 3, 1)
10000
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
