In [2]:
import tensorflow as tf
v = tf.Variable(tf.truncated_normal([2,3]))

vi = v.initialized_value()
vi1 = v.initialized_value()
w = tf.Variable(vi*2.0)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    init.run()
    print(vi.eval())
    print(vi1.eval())
    print(w.eval())

[[ 0.76846212  1.26871157 -1.69233882]
 [ 0.89961743  1.94003499  0.50986147]]
[[ 0.76846212  1.26871157 -1.69233882]
 [ 0.89961743  1.94003499  0.50986147]]
[[ 1.53692424  2.53742313 -3.38467765]
 [ 1.79923487  3.88006997  1.01972294]]
