In [1]:
import tensorflow as tf
import numpy as np

a = np.zeros([2,2])
print(a)

t = tf.zeros([2,2])
sess = tf.Session()
print(sess.run(t))
sess.close()

[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]


In [2]:
import tensorflow as tf

t0 = tf.constant([[1,2,3],[4,5,6]])
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print(sess.run(tf.zeros_like(t0)))

sess.close()

[[0 0 0]
 [0 0 0]]
