In [1]:
#tf.ones([2,3], tf.int32)

import tensorflow as tf

t0 = tf.ones([3,3], tf.int32)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print(sess.run(t0))
print(sess.run(tf.ones_like(t0)))

sess.close()

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
