In [2]:
import tensorflow as tf

t0 = tf.range(3, 18, 3)

t1 = tf.range(3, 1, -0.5)

t2 = tf.range(5)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print(sess.run(t0))
print(sess.run(t1))
print(sess.run(t2))

sess.close()

[ 3  6  9 12 15]
[ 3.   2.5  2.   1.5]
[0 1 2 3 4]
